# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0005_gobuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='subversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.IntegerField(blank=True, choices=[(1, '\u751f\u4ea7\u73af\u5883'), (2, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883')),
                ('svnparentpath', models.CharField(blank=True, default=b'/srv/svn/', max_length=32, null=True)),
                ('svnowner', models.CharField(blank=True, default=b'www-data:www-data', max_length=32, null=True)),
                ('svnrooturl', models.CharField(max_length=32)),
                ('svnusername', models.CharField(max_length=32)),
                ('svnpassword', models.CharField(max_length=32)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.minion')),
            ],
        ),
    ]
