# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0013_auto_20170704_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u8d44\u6e90\u552f\u4e00\u6807\u8bc6')),
                ('category', models.CharField(choices=[(1, 'db'), (2, 'ops')], default='db', max_length=16, verbose_name='\u6240\u5c5e\u7c7b\u522b')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='\u8d44\u6e90\u8bf4\u660e')),
            ],
        ),
        migrations.CreateModel(
            name='ResTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mysql', max_length=32, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='SVCResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_center.Resources')),
                ('svc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.gogroup')),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_center.ResTypes', verbose_name='\u8d44\u6e90\u7c7b\u578b'),
        ),
    ]
