# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.IntegerField(choices=[(1, 'db'), (2, 'ops')], verbose_name='\u6240\u5c5e\u7c7b\u522b'),
        ),
    ]
