# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0002_auto_20170729_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('db', 'db'), ('ops', 'ops')], max_length=16, verbose_name='\u6240\u5c5e\u7c7b\u522b'),
        ),
    ]
