# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winconf',
            name='tasklist_name',
            field=models.CharField(max_length=32),
        ),
    ]
