# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weburl',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.1.1'),
            preserve_default=False,
        ),
    ]
