# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_weburl_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('member', models.ManyToManyField(to='www.webSite')),
            ],
        ),
    ]
