# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='disque cluster alias name')),
                ('addr', models.TextField(blank=True, default='', null=True, verbose_name='cluster address')),
            ],
        ),
    ]
