# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
    ]
