# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('repo', models.CharField(max_length=128)),
                ('localpath', models.CharField(max_length=64)),
            ],
        ),
    ]
