# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160713_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
    ]
