# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='env',
            field=models.IntegerField(blank=True, choices=[(1, '\u751f\u4ea7\u73af\u5883'), (2, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
        migrations.AddField(
            model_name='account',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673aIP'),
        ),
        migrations.AddField(
            model_name='spike',
            name='env',
            field=models.IntegerField(blank=True, choices=[(1, '\u751f\u4ea7\u73af\u5883'), (2, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
        migrations.AddField(
            model_name='spike',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673aIP'),
        ),
    ]
