# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20160713_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.IntegerField(blank=True, choices=[(1, '\u751f\u4ea7\u73af\u5883'), (2, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
    ]
