# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_gostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='crontab_svn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('repo', models.CharField(default=b'http://svn.abc.com/svn/test', max_length=128)),
                ('localpath', models.CharField(default=b'/srv/testsvn', max_length=64)),
                ('project', models.CharField(max_length=64)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.minion')),
            ],
        ),
    ]
