# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_ezdelivery_featurecollection_homepage_popupadmin_voucheradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='gogroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='go group name')),
            ],
        ),
    ]
