# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20170313_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goservices',
            name='name',
            field=models.CharField(max_length=128, verbose_name='goservices services name'),
        ),
    ]
