# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20170401_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoServiceRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Go Service name')),
                ('last_rev', models.IntegerField(verbose_name='latest successful revision')),
                ('last_clock', models.IntegerField(verbose_name='latest successful timestamp')),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u4e3b\u673aIP'),
        ),
    ]
