# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20170704_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoTemplateRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Go Project')),
                ('last_rev', models.IntegerField(verbose_name='latest successful revision')),
                ('last_clock', models.IntegerField(verbose_name='latest successful timestamp')),
            ],
        ),
    ]
