# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20170905_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoTemplateRevision',
        ),
    ]
