# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_delete_gotemplaterevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='wan_ip',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u5916\u7f51IP'),
        ),
    ]
