# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_disquecluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disquecluster',
            name='addr',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='cluster address'),
        ),
    ]
