# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20180307_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisqueCluster',
        ),
    ]
