# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_delete_disquecluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='goservices',
            name='ports',
            field=models.CharField(max_length=128, null=True, verbose_name='ports'),
        ),
    ]
