# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_goservices_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='goservices',
            name='level',
            field=models.CharField(max_length=128, null=True, verbose_name='level'),
        ),
    ]
