# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('remote_ip', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
