# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memcache',
            name='memcacheName',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
