# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 18:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_auto_20180613_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabCmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=64, verbose_name='\u624b\u52a8\u586b\u5165\u7684\u547d\u4ee4')),
                ('auto_cmd', models.CharField(max_length=128, verbose_name='\u81ea\u52a8\u8865\u5168\u7684\u547d\u4ee4')),
                ('frequency', models.CharField(max_length=16, verbose_name='\u6267\u884c\u9891\u7387')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 6, 17, 283945), verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65e5\u671f')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_crontab', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': 'crontab\u547d\u4ee4',
                'verbose_name_plural': 'crontab\u547d\u4ee4',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('path', models.CharField(max_length=64, verbose_name='\u672c\u5730\u8def\u5f84')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 6, 17, 282767), verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65e5\u671f')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_project', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Svn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('repo', models.CharField(default=b'http://svn.abc.com/svn/test', max_length=128)),
                ('local_path', models.CharField(default=b'/srv/testsvn', max_length=64)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 6, 17, 281595), verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65e5\u671f')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_svn', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('salt_minion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minion_of_svn', to='asset.minion', verbose_name='SVN\u6240\u5c5esalt minion')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_of_svn', to=settings.AUTH_USER_MODEL, verbose_name='\u6700\u540e\u66f4\u65b0\u8005')),
            ],
            options={
                'verbose_name': 'SVN',
                'verbose_name_plural': 'SVN',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='svn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svn_of_project', to='project_crontab.Svn', verbose_name='\u9879\u76ee\u7684SVN'),
        ),
        migrations.AddField(
            model_name='project',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_of_project', to=settings.AUTH_USER_MODEL, verbose_name='\u6700\u540e\u66f4\u65b0\u8005'),
        ),
        migrations.AddField(
            model_name='crontabcmd',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_of_crontab', to='project_crontab.Project', verbose_name='Crontab\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='crontabcmd',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_of_crontab', to=settings.AUTH_USER_MODEL, verbose_name='\u6700\u540e\u66f4\u65b0\u8005'),
        ),
    ]
