# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_crontab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabcmd',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 13, 49, 598796), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 13, 49, 597564), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='svn',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 13, 49, 596230), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
