# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publishLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('remote_ip', models.GenericIPAddressField()),
                ('publish_url', models.TextField(default='')),
                ('publish_result', models.TextField(default='')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
