# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOperating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5de5\u5355\u64cd\u4f5c\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u5de5\u5355\u4fee\u6539\u65f6\u95f4')),
                ('content', models.CharField(max_length=4096, verbose_name='\u5de5\u5355\u56de\u590d\u5185\u5bb9')),
                ('result', models.IntegerField(blank=True, choices=[(1, '\u5df2\u6267\u884c'), (2, '\u62d2\u7edd'), (3, '\u8fdb\u884c\u4e2d')], null=True, verbose_name='\u5de5\u5355\u7ed3\u679c')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5de5\u5355\u5904\u7406\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_id', models.CharField(max_length=128, verbose_name='\u5de5\u5355ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('creator', models.CharField(max_length=128, verbose_name='\u5de5\u5355\u521b\u5efa\u4eba')),
                ('content', models.CharField(max_length=4096, verbose_name='\u5de5\u5355\u5185\u5bb9')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5de5\u5355\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u5de5\u5355\u4fee\u6539\u65f6\u95f4')),
                ('state', models.IntegerField(blank=True, choices=[(1, '\u65b0\u521b\u5efa'), (2, '\u8fdb\u884c\u4e2d'), (3, '\u5df2\u5b8c\u6210'), (4, '\u62d2\u7edd')], null=True, verbose_name='\u5de5\u5355\u72b6\u6001')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5de5\u5355\u5904\u7406\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128, verbose_name='\u5de5\u5355\u7c7b\u578b')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5de5\u5355\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u5de5\u5355\u4fee\u6539\u65f6\u95f4')),
                ('state', models.IntegerField(blank=True, choices=[(1, '\u65b0\u521b\u5efa'), (2, '\u8fdb\u884c\u4e2d'), (3, '\u5df2\u5b8c\u6210'), (4, '\u62d2\u7edd')], null=True, verbose_name='\u5de5\u5355\u72b6\u6001')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5de5\u5355\u5904\u7406\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='tickettasks',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TicketType', verbose_name='\u5de5\u5355\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='ticketoperating',
            name='operating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TicketTasks', verbose_name='\u5de5\u5355ID'),
        ),
    ]
