# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettasks',
            name='tasks_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u5de5\u5355ID'),
        ),
    ]
