# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_webinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'web\u7ad9'), (2, 'M\u7ad9')], null=True, verbose_name='\u7ad9\u70b9\u7c7b\u578b'),
        ),
    ]
