# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170319_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettasks',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, '\u65b0\u521b\u5efa'), (2, '\u8fdb\u884c\u4e2d'), (3, '\u5df2\u5b8c\u6210'), (4, '\u62d2\u7edd'), (5, '\u5931\u8d25')], null=True, verbose_name='\u5de5\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, '\u65b0\u521b\u5efa'), (2, '\u8fdb\u884c\u4e2d'), (3, '\u5df2\u5b8c\u6210'), (4, '\u62d2\u7edd'), (5, '\u5931\u8d25')], null=True, verbose_name='\u5de5\u5355\u72b6\u6001'),
        ),
    ]
